/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Revaldi
 */
public class perpustakaan extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        jTxtNama.setEditable(true);
        jTxtNama.setText(null);
        jTxtNim.setText(null);
        jTxtJudul.setText(null);
        CbJenis.setSelectedIndex(0);
        CbDurasi.setSelectedIndex(0);
        jBg1.clearSelection();
        
    }
    
    private void tampilkan_data(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Nama");
        model.addColumn("NIM");
        model.addColumn("Judul Buku");
        model.addColumn("Jenis Buku");
        model.addColumn("Durasi Peminjaman");
        model.addColumn("Jaminan Peminjaman");
        
        try {
            int no=1;
            String sql = "SELECT * FROM pinjam WHERE nama LIKE '%"
                    +jTxtCari.getText()+"%'"
                    + "OR nim LIKE '%"
                    + jTxtCari.getText()+"%'";
                     
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res;
            res = stm.executeQuery(sql);
            
            while (res.next()){
                model.addRow(new Object[]{no++,res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)});
            }
            jTable1.setModel(model);
            
        }catch (SQLException e){
            System.out.println("gagal bos"+ e.getMessage());
        }
    }

    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBg1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtNim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtJudul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CbJenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CbDurasi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTxtCari = new javax.swing.JTextField();
        Rb2 = new javax.swing.JRadioButton();
        Rb1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jLabel1.setText("DATA PEMINJAMAN BUKU PERPUSTAKAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 48, 494, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 128, -1, -1));
        getContentPane().add(jTxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 128, 303, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("NIM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 181, -1, -1));
        getContentPane().add(jTxtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 181, 303, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Judul Buku");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 230, -1, -1));
        getContentPane().add(jTxtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 230, 303, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Jenis Buku");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 291, -1, -1));

        CbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Novel", "Komik", "Karya Tulis Ilmiah", "Jurnal", "Skripsi", "Majalah", "Koran", "Ensiklopedia", "Kitab", " " }));
        getContentPane().add(CbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Durasi  Peminjaman");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 349, -1, -1));

        CbDurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "3 Hari", "5 Hari", "10 Hari" }));
        getContentPane().add(CbDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 348, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Jaminan Peminjaman");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 413, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 128, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-80.png"))); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 514, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-edit-64.png"))); // NOI18N
        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 514, -1, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-delete-bin-100.png"))); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 514, -1, -1));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cancel-100 (1).png"))); // NOI18N
        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 514, -1, -1));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-exit-100.png"))); // NOI18N
        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 595, -1, -1));

        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-client-96.png"))); // NOI18N
        jButton6.setText("Cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 595, -1, -1));
        getContentPane().add(jTxtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 601, 356, 30));

        jBg1.add(Rb2);
        Rb2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Rb2.setText("KTM");
        getContentPane().add(Rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 410, -1, -1));

        jBg1.add(Rb1);
        Rb1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Rb1.setText("KTP");
        getContentPane().add(Rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 410, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wp2561082-simple-background.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            String sql = "SELECT * FROM pinjam WHERE nama LIKE '%"
                    +jTxtCari.getText()+"%'"
                    + "OR nim LIKE '%"
                    + jTxtCari.getText()+"%'";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            
        } catch(HeadlessException | SQLException e){
         
            
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String nama1 = jTable1.getValueAt(baris,1).toString();
        jTxtNama.setText(nama1);
        
        String nim1 = jTable1.getValueAt(baris, 2).toString();
        jTxtNim.setText(nim1);
        
        String judul1 = jTable1.getValueAt(baris, 3).toString();
        jTxtJudul.setText(judul1);
        
        String jenis1 = jTable1.getValueAt(baris, 4).toString();
        CbJenis.setSelectedItem(jenis1);
        
        String durasi1 = jTable1.getValueAt(baris, 5).toString();
        CbJenis.setSelectedItem(durasi1);
        
        if ("KTP".equals(jTable1.getValueAt(baris, 6).toString())){
            Rb1.setSelected(true);
        } else {
            Rb2.setSelected(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String jaminan_edit = null;
        if(Rb1.isSelected()){
            jaminan_edit = "KTP";
        } else {
            jaminan_edit= "KTM";
        }
        
        try{
            String sql = "INSERT INTO pinjam VALUES ('"+ jTxtNama.getText()
                    +"','"+jTxtNim.getText()
                    +"','"+jTxtJudul.getText()
                    +"','"+CbJenis.getSelectedItem()
                    +"','"+CbDurasi.getSelectedItem()
                    +"','"+jaminan_edit+"')";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses simpan data berhasil");
            tampilkan_data();
            kosongkan_form();
            
        }catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String jaminan_edit = null;
        if (Rb1.isSelected()){
            jaminan_edit = "KTP";
        } else {
            jaminan_edit = "KTM";
        }
        
        try {
            String sql = "UPDATE pinjam SET nama ='"+ jTxtNama.getText()
                    +"', nim ='"+jTxtNim.getText()
                    +"', judul ='"+jTxtJudul.getText()
                    +"', jenis ='"+CbJenis.getSelectedItem()
                    +"', durasi ='"+CbDurasi.getSelectedItem()
                    +"', jaminan ='"+jaminan_edit
                    +"'  WHERE nama ='"+jTxtNama.getText() + "'";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(this, "Edit data berhasil !");
        } catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
            String sql = "DELETE FROM pinjam WHERE nama = '" + jTxtNama.getText() + "'";
            java.sql.Connection conn = (Connection) konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "hapus data berhasil...");
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();  
        kosongkan_form();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        kosongkan_form();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbDurasi;
    private javax.swing.JComboBox<String> CbJenis;
    private javax.swing.JRadioButton Rb1;
    private javax.swing.JRadioButton Rb2;
    private javax.swing.ButtonGroup jBg1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCari;
    private javax.swing.JTextField jTxtJudul;
    private javax.swing.JTextField jTxtNama;
    private javax.swing.JTextField jTxtNim;
    // End of variables declaration//GEN-END:variables
}
